### PR TITLE
Invalidating the session expired variable when attempting a new login, or …

### PR DESCRIPTION
**Pull request by aludvigsen**
…else the "session expired" message wil popup several times (blinking) because there several requests still going on.

### CODE REVIEW

**Comment by syastrov** [comment]
retest this please

**Comment by syastrov** [comment]
Hi andreas. I have now added you to the list of users that Jenkins will trigger a test automatically for.

**Comment by aludvigsen** [comment]
@syastrov  That is great (y)

**Comment by syastrov** [comment]
@aludvigsen: Quick question: will the new activities resume polling after a new session has been established?

**Comment by aludvigsen** [comment]
@syastrov Yes :+1: Angular reloads the controllers, so the polling will start again (re-initialized) after login.

**Comment by syastrov** [comment]
Perfect :+1:

**Pull request merged**
