### PR TITLE
OPENE-391 and OPENE-392. Toggle journalnotes and group cases between …

### PR DESCRIPTION
**Pull request by vu-mai**
…list view and grid view

### CODE REVIEW

**Comment by vu-mai** [comment]
retest this please

**Comment by DarkStar1** [comment]
restest this please

**Comment by DarkStar1** [comment]
restest this please

**Comment by DarkStar1** [comment]
restest this please

**Comment by DarkStar1** [comment]
restest this please

**Comment by DarkStar1** [comment]
restest this please

**Pull request merged**
